Repository psyho-pw/sayhoBot, pull requests merged in 2023-05, with the labels that each got.

#20 feat: package version update
  Dockerfile.development
  Dockerfile.production
  package.json
  src/config/config.ts
  yarn.lock
Labels: migrate

#21 Feature/docker
  .dockerignore
  Dockerfile
  Dockerfile.development
  Dockerfile.production
  docker-compose.yml
  package.json
  src/common/validations/base-page-query.dto.ts
  src/song/dto/get-songs.dto.ts
  src/song/song.controller.ts
  src/song/song.service.ts
  yarn.lock
Labels: enhancement

#29 fix: add timezone installation stage
  Dockerfile
Labels: bug

#30 feat: switch package manger to pnpm
  package.json
  pnpm-lock.yaml
  yarn.lock
Labels: enhancement

#31 feat: add env file commands to package.json
  package.json
  pnpm-lock.yaml
Labels: enhancement

#32 feat: add fleet config
  .fleet/run.json
Labels: enhancement
